app = "splitter-app"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DJANGO_SETTINGS_MODULE = "splitter_django.settings"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0