# Generated by Django 5.1.7 on 2025-05-22 18:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MVSepJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("local_file_path", models.CharField(max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "output_dir",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("stem_files_json", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MVSep Job",
                "verbose_name_plural": "MVSep Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_hash", models.CharField(max_length=64, unique=True)),
                (
                    "ghl_contact_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("demo", "Demo Access"),
                            ("monthly", "Monthly Subscription"),
                            ("yearly", "Yearly Subscription"),
                            ("lifetime", "Lifetime Access"),
                        ],
                        default="demo",
                        max_length=20,
                    ),
                ),
                ("has_active_access", models.BooleanField(default=False)),
                ("current_tags", models.JSONField(default=list)),
                ("monthly_limit", models.IntegerField(default=0)),
                ("demo_limit", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_validated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SplitUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_duration_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="splitter.mvsepjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="splitter.useraccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "year", "month"],
                        name="splitter_sp_user_id_ba20b8_idx",
                    )
                ],
            },
        ),
    ]
